name: Terragrunt Plan Dev

on:
  push:
    branches: [dev]
    paths:
      - "terraform/dev/**"
      - "modules/aws/**"

env:
  ECR_URI: ${{ secrets.AWS_ECR_URI }}

  TF_VERSION: 1.0.5
  TG_VERSION: 0.28.7
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: dev

jobs:
  terragrunt:
    name: deploy-dev
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Plan
        id: tg_plan_dev
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          TF_CLI_ARGS: -no-color
          AWS_ECR_URI: ${{ env.ECR_URI }}
        run: terragrunt run-all plan --terragrunt-non-interactive | tee /tmp/tg_plan

      - name: Terragrunt Apply
        id: tg_apply_dev
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          TF_CLI_ARGS: -no-color
          AWS_ECR_URI: ${{ env.ECR_URI }}
        run: terragrunt run-all apply --terragrunt-non-interactive
