name: Terragrunt Plan Sandbox

on:
  push:
    branches: [dev]
    paths: [terraform/sandbox/**]

env:
  ECR_URI: ${{ secrets.AWS_ECR_URI }}

  TF_VERSION: 1.0.5
  TG_VERSION: 0.28.7
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: sandbox

jobs:
  plan:
    name: terragrunt-plan-sandbox
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1

      - id: changes
        name: Any changes?
        run:
          "echo '::set-output name=BUILD::${{env.BUILD_ALL}}'\nfor changed_file in\
          \ ${{ steps.files.outputs.all }}; do\n  echo \"Changed file - do I care? ${changed_file}.\"\
          \n  if  [[ ${changed_file} == dockerfiles/${{env.DOCKER_ITEM}}/* ]] || [[\
          \ ${changed_file} == dockerfiles/Dockerfile.${{env.DOCKER_ITEM}} ]] ;\n  then\n\
          \    echo \"Detected change!\"\n    echo '::set-output name=BUILD::YES'\n\
          \  fi\ndone\n"

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Plan
        id: tg_plan_sandbox
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          TF_CLI_ARGS: -no-color
          AWS_ACCOUNTS_ECR_READ_ACCESS: ${{ secrets.AWS_ACCOUNTS_ECR_READ_ACCESS }}
        run: terragrunt run-all plan --terragrunt-non-interactive | tee /tmp/tg_plan
        continue-on-error: true

      - name: Terragrunt Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
